### ISSUE TITLE
Canceling the confirm prompt produces error

### ISSUE THREAD

**Issue by peteallport** [ricklamers/shell-ai#23]
Canceling the prompt causes the below error...

```bash
macOS:shell-ai user$ shai terraform check
? Select a command: terraform validate
? Confirm: terraform validate
Traceback (most recent call last):
  File "/opt/homebrew/bin/shai", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/shell_ai/main.py", line 171, in main
    ).execute()
      ^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/InquirerPy/base/simple.py", line 336, in execute
    raise KeyboardInterrupt
KeyboardInterrupt
```

**Comment by ricklamers** [comment]
Ah good catch, cleaned it up https://github.com/ricklamers/shell-ai/commit/26f8e19526b85b1108a765273555ca56b2ab7979
